### ISSUE TITLE
Error by Handling Multiple Requests

### ISSUE THREAD

**Issue by Tert0** [Ext-Creators/discord-ext-ipc#22]
Error by Handling Multiple Requests

### Description
```python
@app.route(API_BASE_ROUTE + 'bot/guild', methods=['POST'])
async def isBotOnGuild():
    try:
        data = await request.json
        guild_id: int = data['guild_id']
    except:
        print('Bad Request')
    print(f'Guild_ID: {guild_id}')
    result = await ipc_client.request('is_on_guild', guild_id=guild_id)
    print(f'Result: {result}')
    return {"result": result}
```
My Frontend is sending multiple requets to this Endpoint very fast.

### Actual Behavior
Error
```
[2021-02-24 13:15:58,550] Error in ASGI Framework
Traceback (most recent call last):
  File "/home/username/myproject/venv/lib/python3.9/site-packages/hypercorn/asyncio/context.py", line 39, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/hypercorn/utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/asgi.py", line 33, in __call__
    _raise_exceptions(done)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/asgi.py", line 256, in _raise_exceptions
    raise task.exception()
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/asgi.py", line 72, in handle_request
    response = await self.app.handle_request(request)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1866, in handle_request
    return await self.handle_exception(error)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1118, in handle_exception
    raise error
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1862, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1887, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1104, in handle_user_exception
    raise error
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1885, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1933, in dispatch_request
    return await handler(**request_.view_args)
  File "/home/username/myproject/main.py", line 106, in isBotOnGuild
    result = await ipc_client.request('is_on_guild', guild_id=guild_id)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/discord/ext/ipc/client.py", line 120, in request
    return json.loads(recv.data)
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not RuntimeError
[2021-02-24 13:15:58,552] 127.0.0.1:44610 POST /api/v1/bot/guild 1.1 500 - 47588
[2021-02-24 13:15:58,559] 127.0.0.1:44604 OPTIONS /api/v1/bot/guild 1.1 200 0 23103
[2021-02-24 13:15:58,570] 127.0.0.1:44634 OPTIONS /api/v1/bot/guild 1.1 200 0 27357
Guild_ID: 647535887495856100
[2021-02-24 13:15:58,583] 127.0.0.1:44642 OPTIONS /api/v1/bot/guild 1.1 200 0 16591
Guild_ID: 707601932142772200
Guild_ID: 786606423383212000
[2021-02-24 13:15:58,597] Error in ASGI Framework
Traceback (most recent call last):
  File "/home/username/myproject/venv/lib/python3.9/site-packages/hypercorn/asyncio/context.py", line 39, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/hypercorn/utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/asgi.py", line 33, in __call__
    _raise_exceptions(done)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/asgi.py", line 256, in _raise_exceptions
    raise task.exception()
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/asgi.py", line 72, in handle_request
    response = await self.app.handle_request(request)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1866, in handle_request
    return await self.handle_exception(error)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1118, in handle_exception
    raise error
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1862, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1887, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1104, in handle_user_exception
    raise error
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1885, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/quart/app.py", line 1933, in dispatch_request
    return await handler(**request_.view_args)
  File "/home/username/myproject/main.py", line 106, in isBotOnGuild
    result = await ipc_client.request('is_on_guild', guild_id=guild_id)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/discord/ext/ipc/client.py", line 103, in request
    await self.websocket.send_str(json.dumps(fmt))
  File "/home/username/myproject/venv/lib/python3.9/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/home/username/myproject/venv/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
[2021-02-24 13:15:58,599] 127.0.0.1:44638 POST /api/v1/bot/guild 1.1 500 - 55090
```

### Expected Behavior
No Error
Handling requests step by step

### Reproduction Steps
Send many Requets very fast

### Checklist

- [x] I have searched open issues for duplicates.
- [] I have shown the entire traceback, if applicable.
- [x] I have removed any access tokens from display, if applicable.

### System Information
Arch Linux (5.10.16-arch1-1)
Python 3.9.1

**Comment by lgaan** [comment]
I am unsure at the moment of the cause of this, however the recent transition to `send_json(...)` instead of `send_str(json.dumps(...)` may provide a fix for this.

I'll leave this open for the time being.

**Comment by Gobot1234** [comment]
That shouldn't make any difference since one is just shorthand for the other

**Comment by Tert0** [comment]
The problem was not the many requests but a bug in my programme so I will close the issue.

**Comment by anselal** [comment]
I also get `ConnectionResetError Cannot write to closing transport` after some hours.
Seems that the connection is closing, it logs you out, which I guess is normal.

But how do we handle this exception ?

Specifically I am getting a long debug message in the browser.

One of the errors is when I call `guild_count = await ipc_client.request("get_guild_count")` I get `	{'error': 'IPC Server Unreachable, restart client process.', 'code': 500}`

But it is not a solution to restart the client every now and then. How can my dashboard be "alive" if I have to restart it every couple of hours ?

Any hints ??
